<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>错误捕获</title>
</head>

<body>
  <script src="../../promise.js"></script>
  <!-- <script src="../../test.js"></script> -->
  <script>
    // 错误捕获
    // var promise = new Promise((resolve, reject) => {
    //   throw new Error('I am an error')
    // }).catch((err) => {
    //   console.log(err)
    // })

    // promise 在 resolve 后面再抛错不会被捕获
    var promise = new Promise((resolve, reject) => {
      resolve('success')
      throw new Error('I am an error')
    })
      .then((fullfilled) => {
        console.log(fullfilled)
      })
      .catch((err) => {
        console.log(err)
      })
  </script>
</body>

</html>